---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html/zacma
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env.production $DEPLOYPATH/.env
    - cd $DEPLOYPATH
    - /usr/local/bin/php artisan storage:link || true
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan migrate --force
